#!/bin/sh

CONF_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/mosquitto

BIN_DIR=$ADDON_DIR/bin

Stop () {
    echo -n "Stopping Mosquitto: "
    start-stop-daemon -K -q -p /var/run/mosquitto.pid && echo "OK"
}

Start () {
    echo -n "Starting Mosquitto: "
    if [ -f /etc/config/server.pem ]; then
        if [ -f $ADDON_DIR/etc/conf.d/listener-mqtts.conf.disabled ]; then
            mv $ADDON_DIR/etc/conf.d/listener-mqtts.conf.disabled $ADDON_DIR/etc/conf.d/listener-mqtts.conf
            mv $ADDON_DIR/etc/conf.d/listener-wss.conf.disabled $ADDON_DIR/etc/conf.d/listener-wss.conf
        fi
    else
        if [ -f $ADDON_DIR/etc/conf.d/listener-mqtts.conf ]; then
            mv $ADDON_DIR/etc/conf.d/listener-mqtts.conf $ADDON_DIR/etc/conf.d/listener-mqtts.conf.disabled
            mv $ADDON_DIR/etc/conf.d/listener-wss.conf $ADDON_DIR/etc/conf.d/listener-wss.conf.disabled
        fi
    fi
    export LD_LIBRARY_PATH=$ADDON_DIR/lib
    start-stop-daemon -S -b -m -p /var/run/mosquitto.pid --exec $ADDON_DIR/bin/mosquitto -- -c $ADDON_DIR/etc/mosquitto.conf && echo "OK"
}

case "$1" in

  stop)
    Stop
  ;;

  start)
    Start
  ;;

  restart)
    Stop
    sleep 3
    Start
  ;;

  info)
    echo "Info: <center><a href=\"https://mosquitto.org/\" target=\"_blank\"><img width=\"240\" src="/addons/mosquitto/mosquitto-text-side-28.png"></a></center>"
    echo "Name: Mosquitto"
    echo "Version: 1.5.8+2"
    echo "Update: /addons/mosquitto/update_check.cgi"
    echo "Operations: uninstall restart"
  ;;

  uninstall)
     /usr/bin/killall mosquitto
     rm /var/run/mosquitto.pid
     rm $CONF_DIR/rc.d/mosquitto
     rm $BIN_DIR/mosquitto*
     rm $CONF_DIR/addons/www/mosquitto
     rm -r $ADDON_DIR

     # Delete libs only if broken links
     find -L /usr/local/lib/libcrypto.so* -type l -delete
     find -L /usr/local/lib/libev.so* -type l -delete
     find -L /usr/local/lib/libssl.so* -type l -delete
     find -L /usr/local/lib/libwebsockets.so* -type l -delete
     find -L /usr/local/lib/libmosquitto.so* -type l -delete
     find -L /usr/local/lib/libmosquittopp.so* -type l -delete
  ;;

  *)
    echo "Usage: mosquitto {start|stop|restart|info|uninstall}" >&2
    exit 1
  ;;

esac



exit 0