#!/bin/sh

ADDONS_DIR=/usr/local/addons
MSQ_DIR=$ADDONS_DIR/mosquitto


BIN_DIR=/usr/local/bin
LIB_DIR=/usr/local/lib
CONF_DIR=/usr/local/etc/config

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

mkdir -p $ADDONS_DIR && chmod 755 $ADDONS_DIR 

if [ -f $CONF_DIR/rc.d/mosquitto ]; then
    $CONF_DIR/rc.d/mosquitto stop
fi

cp -af mosquitto $ADDONS_DIR/

ln -sf $MSQ_DIR/rc.d/mosquitto $CONF_DIR/rc.d/mosquitto
ln -sf $MSQ_DIR/www $CONF_DIR/addons/www/mosquitto

# Migration

if [ -f $MSQ_DIR/etc/conf.d/mqtt-listener.conf ]; then
    rm $MSQ_DIR/etc/conf.d/mqtt-listener.conf
fi

if [ -f $MSQ_DIR/etc/conf.d/ws-listener.conf ]; then
    rm $MSQ_DIR/etc/conf.d/ws-listener.conf
fi

if [ -f $LIB_DIR/libcrypto.so.1.1 ]; then
    rm $LIB_DIR/libcrypto.so.1.1
fi

if [ -f $LIB_DIR/libev.so ]; then
    rm $LIB_DIR/libev.so*
fi

if [ -f $LIB_DIR/libmosquitto.so ]; then
    rm $LIB_DIR/libmosquitto*
fi

if [ -f $LIB_DIR/libssl.so.1.1 ]; then
    rm $LIB_DIR/libssl.so.1.1
fi

if [ -f $LIB_DIR/libwebsockets.so ]; then
    rm $LIB_DIR/libwebsockets.so*
fi

if [ -f $BIN_DIR/mosquitto ]; then
    rm $BIN_DIR/mosquitto*
fi

sync

/etc/config/rc.d/mosquitto start

exit 0
