#!/bin/sh

ADDONS_DIR=/usr/local/addons
MSQ_DIR=$ADDONS_DIR/mosquitto


BIN_DIR=/usr/local/bin
LIB_DIR=/usr/local/lib
CONF_DIR=/usr/local/etc/config

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

mkdir -p $ADDONS_DIR && chmod 755 $ADDONS_DIR 
mkdir -p $BIN_DIR && chmod 755 $BIN_DIR
mkdir -p $LIB_DIR && chmod 755 $LIB_DIR

if [ -f $CONF_DIR/rc.d/mosquitto ]; then
    $CONF_DIR/rc.d/mosquitto stop
fi

cp -af mosquitto $ADDONS_DIR/

ln -s $MSQ_DIR/lib/* /usr/local/lib/
ln -sf $MSQ_DIR/bin/* /usr/local/bin/
ln -sf $MSQ_DIR/rc.d/mosquitto $CONF_DIR/rc.d/mosquitto
ln -sf $MSQ_DIR/www $CONF_DIR/addons/www/mosquitto

# Migration

if [ -f $MSQ_DIR/etc/conf.d/mqtt-listener.conf ]; then
    rm $MSQ_DIR/etc/conf.d/mqtt-listener.conf
fi

if [ -f $MSQ_DIR/etc/conf.d/tls-listener.conf ]; then
    rm $MSQ_DIR/etc/conf.d/tls-listener.conf
fi

sync

exit 0
